name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: lukka/get-cmake@latest
    - name: pip
      run: pip install --upgrade conan
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release . && cmake --build .
